# === Generated by BahasaFlores Compiler ===
# Jangan edit file ini secara manual!

def sapa(nama):
    print((('Halo ' + nama) + '!'))

def tambah(a, b):
    return (a + b)

x = input('Masukkan angka: ')
x = int(x)
nilai = tambah(x, 10)
print(('Hasil: ' + str(nilai)))
if (nilai > 20):
    print('Angkanya besar')
elif (nilai == 20):
    print('Pas dua puluh')
else:
    print('Angkanya kecil')
for i in range(3):
    print(i)
while (x > 0):
    print(x)
    x = (x - 1)
sapa('Flores')
print('')
print('Program Selesai')
input('Tekan Enter untuk keluar...')