# === Generated by BahasaFlores Compiler ===
# Jangan edit file ini secara manual!

def faktorial(n):
    if (n == 0):
        return 1
    else:
        return (n * faktorial((n - 1)))

def pangkat(basis, eksponen):
    hasil = 1
    for i in range(eksponen):
        hasil = basis
    return hasil

def cek_genap(n):
    if ((n % 2) == 0):
        return True
    else:
        return False

def garis():
    print('================================')

def header(judul):
    garis()
    print(judul)
    garis()

header('  SELAMAT DATANG DI BAHASAFLORES')
print('  Compiler Bahasa Daerah Flores')
print('  Teknik Kompilasi - UNPAM 2025')
garis()
print('Masukkan nama Anda:')
nama = input('> ')
print('Masukkan angka pertama (1-7):')
angka1 = input('> ')
angka1 = int(angka1)
print('Masukkan angka kedua (1-7):')
angka2 = input('> ')
angka2 = int(angka2)
print('')
print((('Halo ' + nama) + '! Berikut semua hasil:'))
header('  1. OPERASI ARITMATIKA')
hasil_tambah = (angka1 + angka2)
hasil_kurang = (angka1 - angka2)
hasil_kali = (angka1 * angka2)
print(((((('  ' + str(angka1)) + ' + ') + str(angka2)) + ' = ') + str(hasil_tambah)))
print(((((('  ' + str(angka1)) + ' - ') + str(angka2)) + ' = ') + str(hasil_kurang)))
print(((((('  ' + str(angka1)) + ' x ') + str(angka2)) + ' = ') + str(hasil_kali)))
header('  2. FAKTORIAL')
fakt1 = faktorial(angka1)
fakt2 = faktorial(angka2)
print(((('  ' + str(angka1)) + '! = ') + str(fakt1)))
print(((('  ' + str(angka2)) + '! = ') + str(fakt2)))
header('  3. PERPANGKATAN')
hasil_p1 = pangkat(angka1, 3)
hasil_p2 = pangkat(angka2, 2)
print(((('  ' + str(angka1)) + ' pangkat 3 = ') + str(hasil_p1)))
print(((('  ' + str(angka2)) + ' pangkat 2 = ') + str(hasil_p2)))
header('  4. GENAP / GANJIL')
if cek_genap(angka1):
    print((('  ' + str(angka1)) + ' adalah GENAP'))
else:
    print((('  ' + str(angka1)) + ' adalah GANJIL'))
if cek_genap(angka2):
    print((('  ' + str(angka2)) + ' adalah GENAP'))
else:
    print((('  ' + str(angka2)) + ' adalah GANJIL'))
header(('  5. TABEL PERKALIAN ' + str(angka1)))
for i in range(10):
    hasil_tabel = (angka1 * (i + 1))
    print(((((('  ' + str(angka1)) + ' x ') + str((i + 1))) + ' = ') + str(hasil_tabel)))
header('  6. CEK GENAP/GANJIL 1-10')
for i in range(10):
    angka_cek = (i + 1)
    if cek_genap(angka_cek):
        print((('  ' + str(angka_cek)) + ' = GENAP'))
    else:
        print((('  ' + str(angka_cek)) + ' = GANJIL'))
header('  7. PERBANDINGAN')
if (angka1 > angka2):
    print(((('  ' + str(angka1)) + ' lebih besar dari ') + str(angka2)))
elif (angka1 == angka2):
    print(((('  ' + str(angka1)) + ' sama dengan ') + str(angka2)))
else:
    print(((('  ' + str(angka1)) + ' lebih kecil dari ') + str(angka2)))
garis()
print((('  Terima kasih, ' + nama) + '!'))
print('  Program BahasaFlores selesai!')
print('  Universitas Pamulang - Teknik Informatika')
garis()
print('')
input('Tekan Enter untuk keluar...')