# src/codegen.py
# ============================================================
#  CODE GENERATOR — AST → Python source code
# ============================================================

from .ast_nodes import *
from typing import List


class CodeGenerator:
    def __init__(self):
        self.indent_level = 0
        self.output: List[str] = []

    def indent(self) -> str:
        return "    " * self.indent_level

    def emit(self, line: str):
        self.output.append(self.indent() + line)

    def generate(self, node: ASTNode) -> str:
        self.output = []
        self.emit("# === Generated by BahasaFlores Compiler ===")
        self.emit("# Jangan edit file ini secara manual!")
        self.emit("")
        self.gen(node)
        return "\n".join(self.output)

    def gen(self, node: ASTNode):
        method = f"gen_{type(node).__name__}"
        visitor = getattr(self, method, None)
        if visitor:
            return visitor(node)
        raise NotImplementedError(f"CodeGen: node {type(node).__name__} belum diimplementasikan")

    def gen_expr(self, node: ASTNode) -> str:
        """Generate expression sebagai string (inline)."""
        method = f"expr_{type(node).__name__}"
        visitor = getattr(self, method, None)
        if visitor:
            return visitor(node)
        raise NotImplementedError(f"CodeGen expr: {type(node).__name__}")

    # ── Program ─────────────────────────────────────────────

    def gen_Program(self, node: Program):
        for stmt in node.body:
            self.gen(stmt)

    # ── Statements ──────────────────────────────────────────

    def gen_AssignStmt(self, node: AssignStmt):
        val = self.gen_expr(node.value)
        self.emit(f"{node.name} {node.op} {val}")

    def gen_PrintStmt(self, node: PrintStmt):
        args = ", ".join(self.gen_expr(a) for a in node.args)
        self.emit(f"print({args})")

    def gen_ExprStmt(self, node: ExprStmt):
        self.emit(self.gen_expr(node.expr))

    def gen_IfStmt(self, node: IfStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if {cond}:")
        self.indent_level += 1
        for stmt in node.then_block:
            self.gen(stmt)
        self.indent_level -= 1

        for ec, eb in node.elif_clauses:
            econd = self.gen_expr(ec)
            self.emit(f"elif {econd}:")
            self.indent_level += 1
            for stmt in eb:
                self.gen(stmt)
            self.indent_level -= 1

        if node.else_block:
            self.emit("else:")
            self.indent_level += 1
            for stmt in node.else_block:
                self.gen(stmt)
            self.indent_level -= 1

    def gen_WhileStmt(self, node: WhileStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"while {cond}:")
        self.indent_level += 1
        for stmt in node.body:
            self.gen(stmt)
        self.indent_level -= 1

    def gen_ForStmt(self, node: ForStmt):
        it = self.gen_expr(node.iterable)
        self.emit(f"for {node.var} in {it}:")
        self.indent_level += 1
        for stmt in node.body:
            self.gen(stmt)
        self.indent_level -= 1

    def gen_FuncDef(self, node: FuncDef):
        params = ", ".join(node.params)
        self.emit(f"def {node.name}({params}):")
        self.indent_level += 1
        for stmt in node.body:
            self.gen(stmt)
        self.indent_level -= 1
        self.emit("")

    def gen_ReturnStmt(self, node: ReturnStmt):
        if node.value:
            self.emit(f"return {self.gen_expr(node.value)}")
        else:
            self.emit("return")

    def gen_BreakStmt(self, node: BreakStmt):
        self.emit("break")

    def gen_ContinueStmt(self, node: ContinueStmt):
        self.emit("continue")

    def gen_InputStmt(self, node: InputStmt):
        if node.prompt:
            return f"input({self.gen_expr(node.prompt)})"
        return "input()"

    # ── Expressions ─────────────────────────────────────────

    def expr_NumberLiteral(self, n: NumberLiteral) -> str:
        return repr(n.value)

    def expr_StringLiteral(self, n: StringLiteral) -> str:
        return repr(n.value)

    def expr_BoolLiteral(self, n: BoolLiteral) -> str:
        return "True" if n.value else "False"

    def expr_NoneLiteral(self, n: NoneLiteral) -> str:
        return "None"

    def expr_Identifier(self, n: Identifier) -> str:
        return n.name

    def expr_BinOp(self, n: BinOp) -> str:
        L = self.gen_expr(n.left)
        R = self.gen_expr(n.right)
        op_map = {
            'atau': 'or',
            'mo dia': 'and',
            'trada': 'not',
        }
        op = op_map.get(n.op, n.op)
        return f"({L} {op} {R})"

    def expr_UnaryOp(self, n: UnaryOp) -> str:
        op_map = {'trada': 'not ', '-': '-'}
        op = op_map.get(n.op, n.op)
        return f"({op}{self.gen_expr(n.operand)})"

    def expr_FuncCall(self, n: FuncCall) -> str:
        args = ", ".join(self.gen_expr(a) for a in n.args)
        return f"{n.name}({args})"

    def expr_InputStmt(self, n: InputStmt) -> str:
        if n.prompt:
            return f"input({self.gen_expr(n.prompt)})"
        return "input()"

    def expr_SubscriptExpr(self, n: SubscriptExpr) -> str:
        return f"{self.gen_expr(n.obj)}[{self.gen_expr(n.index)}]"